routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/', function () {
  return view('welcome');
});
Route::get('/sellers', 'Auth\RegisterController@showRegistrationForm')->name('seller');
Route::get('/confirm-account/{id}', 'Auth\RegisterController@confirmAccount')->name('confirm-account');
Route::get('/verify/{id}', 'Auth\RegisterController@verifyPage')->name('verify');
Route::get('/resend-register-email/{id}', 'Auth\RegisterController@resendRegisterEmail')->name('resend-register-email');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/front-search', 'HomeController@frontSearch');
Route::any('/sort-search', 'HomeController@searchShort');
Route::any('/template/{id}', 'HomeController@template');

Route::any('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::any('/support-center', 'HomeController@supportCenter')->name('support-center');
Route::get('/support-center/{id}/{question}', 'HomeController@supportCatoryWise');
Route::get('/support-center-answer/{id}/{question}', 'HomeController@supportCenterAnswer');

//Route::any('/support-search', 'HomeController@supportSearch');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('/events', 'HomeController@events')->name('events');
Route::get('/careers', 'HomeController@careers')->name('careers');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{slug}', 'HomeController@categoryWise')->name('category-wise');

Route::get('/payment-view/{id}', 'PaymentController@paymentView')->name('payment-view');

if(!function_exists('adminRoutes')) {
  function adminRoutes() {
    Route::group(['namespace' => 'Admin','middleware' => 'disablepreventback'], function()
    {
      Route::resource('dashboard', 'DashboardController');
      Route::get('settings', 'DashboardController@settings');
      Route::post('postCredentials', 'DashboardController@postCredentials');
      Route::post('updateimage', 'DashboardController@updateImage');
      Route::any('uploadSingleImage', 'DashboardController@uploadSingleImage');
      Route::post('deleteSingleImage', 'DashboardController@deleteSingleImage');
      Route::resource('sellers', 'SellersController');
      Route::any('search-sellers', 'SellersController@searchSellers');
      Route::post('change-status', 'SellersController@changeStatus');
      Route::any('entriesperpage', 'SellersController@entriesperpage');
      Route::post('deactivate-seller', 'SellersController@deactivateSeller');
      Route::resource('buyers', 'BuyersController');
      Route::any('search-buyers', 'BuyersController@searchBuyers');
      Route::any('entriesperpage', 'BuyersController@entriesperpage');
      Route::post('deactivate-buyer', 'BuyersController@deactivateBuyer');
      Route::resource('subscription_plan', 'SubscriptionplanController');
      Route::get('subscription', 'SubscriptionplanController@subscription');
      Route::get('new-subscription', 'SubscriptionplanController@newSubscription');
      Route::any('seller-design/{id}', 'SellersController@sellerDesign');
      Route::any('seller-logs/{id}/{designid}', 'SellersController@sellerLogs');

      Route::resource('events', 'EventController');

      Route::resource('orders', 'OrderController');
      Route::any('search-orders', 'OrderController@searchOrders');
      Route::get('order-details/{id}', 'OrderController@orderDetail');

      Route::get('transactions', 'TransactionController@index');
      Route::any('search-transaction', 'TransactionController@searchTransaction');

      Route::resource('faq', 'FaqController');
      Route::post('edit-modal', 'FaqController@editModal');
      // support center
      Route::resource('support-center', 'SupportCenterController');
      Route::post('edit-support-modal', 'SupportCenterController@editModal');

      Route::resource('support-category', 'SupportCategoryController');
      Route::post('support-category-modal', 'SupportCategoryController@supportCategoryModal');
    });
  }
}
if(!function_exists('buyerRoutes')) {
  function buyerRoutes() {
    Route::group(['namespace' => 'Buyer','middleware' => 'disablepreventback'], function()
    {
      Route::resource('/', 'DashboardController');
      //Route::resource('/dashboard', 'DashboardController');
      Route::resource('/dashboard', 'AccountSettingsController');
      Route::resource('/account-settings', 'AccountSettingsController');
      // Route::get('/resend-register-email/{id}', 'AccountSettingsController@resendRegisterEmail');
      Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
      Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfoBuyer');
      Route::post('/addRatingFaviorite','DashboardController@addRatingFaviorite')->name('addRatingFaviorite');
      Route::resource('/favourite','FavoriteController');
      Route::get('/downloads','FavoriteController@downloads');
      Route::get('/edit-template/{id}', 'FavoriteController@editTemplate');
      Route::any('search-downloads', 'FavoriteController@searchDownload');
      Route::any('uploadSingleImage', 'FavoriteController@uploadSingleImage');
      Route::any('/add-to-cart', 'CartController@addToCart');
      Route::any('/cart', 'CartController@index');
      Route::any('/cart-list', 'CartController@cartList');
      Route::any('/delete-update-cart-item', 'CartController@removeUpdateFromCart');
      Route::get('/checkout', 'CheckoutController@index')->name('checkout');
      Route::any('/payment-with-paypal', 'CheckoutController@paypalWithPayment')->name('payment.paypal');
      Route::get('/paypal-success', 'CheckoutController@paypalSuccess')->name('payment.paypalSuccess');

      Route::resource('orders', 'OrderController');
      Route::get('order-details/{id}', 'OrderController@orderDetail');
      Route::post('addRatingReview', 'FavoriteController@addRatingReview');
      Route::any('getRatingReview', 'FavoriteController@getRatingReview');


    });
  }
}
if(!function_exists('sellerRoutes')) {
  function sellerRoutes() {
    Route::group(['namespace' => 'Seller','middleware' => 'disablepreventback'], function() {
      //Route::group(['middleware' => 'plan'], function() {
      Route::group([], function() {
        Route::resource('/', 'DashboardController');
        Route::resource('dashboard', 'DashboardController');
        Route::resource('account-settings', 'AccountSettingsController');
        Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
        Route::resource('portfolio', 'DesignController');
        Route::post('geteditdesignmodal', 'DesignController@getEditDesignModal');
        Route::any('uploadSingleImage', 'DesignController@uploadSingleImage');

        Route::get('uploads', 'DesignController@getUploads')->name('uploads');
        Route::any('search-uploads', 'DesignController@searchUploads');
        Route::post('addFont', 'DesignController@addFont');

        Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfo');
        Route::any('/getImageEditor', 'DesignController@getImageEditor');

        Route::resource('earnings', 'EarningController');
        Route::any('search-earnings', 'EarningController@searchEarnings');
        Route::any('get_earning_details', 'EarningController@get_earning_details');
        Route::any('download-csv', 'EarningController@earningsExport');
      });

      Route::resource('choose_plan', 'ChoosePlanController');
    });
  }
}
Route::group(['prefix' => 'admin','middleware' => ['auth','role:admin','design']], function()
{
  adminRoutes();
});
Route::group(['prefix' => 'buyer','middleware' => ['auth','role:buyer']], function()
{
  buyerRoutes();
});
Route::group(['prefix' => 'seller','middleware' => ['auth','role:seller','verified']], function()
{
  sellerRoutes();
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Subscriptionplan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subscriptionplan extends Model
{
  protected $table 	= 'subscription_plan';
  protected $fillable = ['id', 'title', 'color', 'price', 'offerprice', 'uploads', 'storage', 'storagelimit', 'description', 'image', 'status', 'addedby'];
  public $timestamps  = true;
}

app/Http/Controllers/Admin/SubscriptionplanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SubscriptionplanRequest;
use App\Models\Subscriptionplan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Redirect;
use DB;

class SubscriptionplanController extends Controller
{
  public $prefix='';
  public function __construct()
  {
    $this->url    =  url(request()->route()->getPrefix());
    $this->prefix = 'admin/subscriptionplan';
    $this->title  = 'Subscriptionplan';
  }
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {

    $data = array();
    $getAllSubscriptionplan = Subscriptionplan::orderBy('id','DESC')->get()->toArray();
    return view($this->prefix.'/subscriptionplan',['url'=>$this->url,'title'=>$this->title,'getAllSubscriptionplan'=>$getAllSubscriptionplan]);
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    try {
      $title = "Add Subscription Plan";
      $button_name = "Save new plan";
      $subUploads = array('5'=>'5','50'=>'50','150'=>'150','250'=>'250',);
      $uploadSize = array('MB'=>'MB','GB'=>'GB','TB'=>'TB',);
      $type = "New";
      return view($this->prefix.'/add',['url'=>$this->url,'type'=>$type, 'title'=>$title,'uploadSize'=>$uploadSize,'subUploads'=>$subUploads, 'button_name'=>$button_name,'data'=>[],'id'=>null]);
    } catch (\Exception $e) {
      DB::rollback();
      return response()->json(['errors'=>['message'=>$e->getMessage()]],400);
    }
  }

  public function store(Request $request)
  {
    try
    {
      $id=null;
      if(!empty($request->id))
      {
        $id = \Crypt::decryptString($request->id);
        $action = 'updated';
      }else {
        $action = 'added';
      }
      DB::beginTransaction();
      $request->title=trim($request->title);

      if($request->hasfile('image'))
      {
        $image = $request->file('image');
        $image_name = time().'_'.$image->getClientOriginalName();
        $img_path = base_path().'/assets/images/';
        $image->move($img_path, $image_name);
        $image_name = $image_name;
      }else {
        $image_name = '';
      }
      // echo $image_name; die;
      $createData = array(
        'title' => $request->title,
        'price' => $request->price,
        'offerprice' => $request->offerprice,
        'uploads' => $request->uploads,
        'storage' => $request->storage,
        'storagelimit' => $request->storagelimit,
        'color' => $request->color,
        'status' => $request->status,
        'addedby' => Auth::user()->id,
        'image' => $image_name,
      );
      // echo '<pre>'.$id;
      // print_r($createData); die;
      if(Subscriptionplan::updateOrCreate(['id'=>$id],$createData))
      {
        DB::commit();
        $res['success']         = true;
        $res['url']             = $this->url.'/subscription_plan';
        $res['delayTime']       = '2000';
        $res['success_message']   = 'Plan has been '.$action.' successfully.';
      }
      else
      {
        DB::rollback();
        $res['success']         = false;
        $res['url']             = $this->url.'/subscription_plan/create';
        $res['delayTime']       = '2000';
        $res['error_message']   = 'Something went wrong.';
      }
      echo json_encode($res);
      die();
    }
    catch (\Exception $e)
    {
      DB::rollback();
      $errors             =$e->getMessage();
      $res['success']     = false;
      $res['formErrors']  = true;
      $res['errors']      = $errors;
      echo json_encode($res);
      die();
    }
  }



  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    try {
      $title = "Edit Subscription Plan";
      $button_name = "Edit Plan";
      $pass_id = $id;
      $subUploads = array('5'=>'5','50'=>'50','150'=>'150','250'=>'250',);
      $uploadSize = array('MB'=>'MB','GB'=>'GB','TB'=>'TB');
      $id = Crypt::decryptString($id);
      $data = Subscriptionplan::where('id',$id)->first();
      $type = "Edit";
      return view($this->prefix.'/edit',['url'=>$this->url,'type'=>$type, 'title'=>$title,'uploadSize'=>$uploadSize, 'subUploads'=>$subUploads, 'button_name'=>$button_name,'data'=>$data,'id'=>$pass_id]);
    } catch (\Exception $e) {
      DB::rollback();
      return response()->json(['errors'=>['message'=>$e->getMessage()]],400);
    }
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    try
    {
      $id=null;
      if(!empty($request->id))
      {
        $id = \Crypt::decryptString($request->id);
        $action = 'updated';
      }else {
        $action = 'added';
      }
      DB::beginTransaction();
      $request->title=trim($request->title);

      if($request->hasfile('image'))
      {
        $image = $request->file('image');
        $image_name = time().'_'.$image->getClientOriginalName();
        $img_path = base_path().'/assets/images/';
        $image->move($img_path, $image_name);
        $image_name = $image_name;
        $createData = array(
          'title' => $request->title,
          'price' => $request->price,
          'offerprice' => $request->offerprice,
          'uploads' => $request->uploads,
          'storage' => $request->storage,
          'storagelimit' => $request->storagelimit,
          'color' => $request->color,
          'status' => $request->status,
          'addedby' => Auth::user()->id,
          'image' => $image_name,
        );
      }
      else
      {
        $createData = array(
          'title' => $request->title,
          'price' => $request->price,
          'offerprice' => $request->offerprice,
          'uploads' => $request->uploads,
          'storage' => $request->storage,
          'storagelimit' => $request->storagelimit,
          'color' => $request->color,
          'status' => $request->status,
          'addedby' => Auth::user()->id
        );
      }
      // echo '<pre>'.$id;
      // print_r($createData); die;
      if(Subscriptionplan::updateOrCreate(['id'=>$id],$createData))
      {
        DB::commit();
        $res['success']         = true;
        $res['url']             = $this->url.'/subscription_plan';
        $res['delayTime']       = '2000';
        $res['success_message']   = 'Plan has been '.$action.' successfully.';
      }
      else
      {
        DB::rollback();
        $res['success']         = false;
        $res['url']             = $this->url.'/subscription_plan/create';
        $res['delayTime']       = '2000';
        $res['error_message']   = 'Something went wrong.';
      }
      echo json_encode($res);
      die();
    }
    catch (\Exception $e)
    {
      DB::rollback();
      $errors             =$e->getMessage();
      $res['success']     = false;
      $res['formErrors']  = true;
      $res['errors']      = $errors;
      echo json_encode($res);
      die();
    }
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    $user = Subscriptionplan::find($id);
    if($user->delete())
    {
      $data['success']          = true;
      $data['Subscriptionplan'] = 'deleted';
      $data['success_message']  = 'Subscription plan delete Successfully.';
    }
    else
    {
      $data['success']          = false;
      $data['Subscriptionplan'] = 'not delete';
      $data['success_message']  = 'Subscription plan delete failed.';
    }
    echo json_encode($data); die();
  }
  public function subscription()
  {
    return view('admin/subscriptionplan/subscription', ['url'=>$this->url]);
  }

  public function newSubscription()
  {
    return view('admin/subscriptionplan/new-subscription', ['url'=>$this->url]);
  }

}

resources/views/admin/subscriptionplan/add.blade.php
@extends('layouts.admin')
@section('content')
<div id="wrapper">
	<div class="page_title">
		<div class="row">
			<div class="col-md-2">
				<a class="back_to" href="{{ $url.'/subscription_plan' }}"><< Back to Plans</a>
			</div>
			<div class="col-md-10">
				<h1>{{ $type }} Subscription Plan</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6 col-md-10 col-12 offset-md-2">
			<div class="seller_details Subscriptions_Plans">
				{!! Form::model($data,['action' => 'Admin\SubscriptionplanController@store', 'method' => 'post', 'files' => true,'id'=>'subscription-plan-form']) !!}
				<div class="form-group">
					<div class="row">

						<div class="col-md-3">
							<label>Plan name</label>
						</div>
						<div class="col-md-9">
							{{ Form::text('title', null, array_merge(['class' => 'form-control', 'id' => 'title', 'placeholder' => 'Enter plan name'])) }}
							@if ($errors->has('title'))

							<label class="error">{{ $errors->first('title') }}</label>

							@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-3">
							<label>Uploads</label>
						</div>
						<div class="col-md-9">
							<div class="row">
								<div class="col-md-4">
									<?php //print_r($data['storage']); ?>
									{{ Form::select('uploads', $subUploads, 'S', ['id'=>'uploads','class'=>'form-control'. ( $errors->has('uploads') ? ' is-invalid' : '') ]) }}
									@if ($errors->has('uploads'))
									<label class="error">{{ $errors->first('uploads') }}</label>
									@endif
								</div>
								<div class="col-md-8">
									<div class="row">
										<div class="col-md-3 text-right">
											<label style="min-width:inherit;">Storage</label>
										</div>
										<div class="col-md-4">
											{{ Form::select('storage', $subUploads, 'S', ['id'=>'uploads','class'=>'form-control'. ( $errors->has('storage') ? ' is-invalid' : '') ]) }}
											@if ($errors->has('storage'))
											<label class="error">{{ $errors->first('storage') }}</label>
										</span>
										@endif
									</div>
									<div class="col-md-5">
										{{ Form::select('storagelimit', $uploadSize, 'S', ['id'=>'uploads','class'=>'form-control'. ( $errors->has('storagelimit') ? ' is-invalid' : '') ]) }}
										@if ($errors->has('storagelimit'))
										<label class="error">{{ $errors->first('storagelimit') }}</label>
									</span>
									@endif
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-3">
					<label style="color:#009ab1;">Upload Icon</label>
				</div>
				<div class="col-md-9">
					<div class="row">
						<div class="col-md-4">
							<div class="form-group">
								<button style="display:block;width:100px; height:30px;" onclick="document.getElementById('user_photo').click()" type="button">Choose File</button>
								<label style="display:none;" id="user_photo-name">Please Select Image</label>
								{{ Form::file('image', array_merge(['class' => 'custom-file-input', 'id' => 'user_photo','style'=>"visibility:hidden;"])) }}
								<label class="error" style="display:none;" id="user_photo-error">Please Select Image</label>
								<label class="error" style="display:none;" id="user_photo-valierror">Invalid File Upload</label>
							</div>
						</div>
						<div class="col-md-8">
							<a href="#" id="hidden-input" class="Choose_plan_color demo">Choose plan color</a>
							{{ Form::hidden('color', null, array_merge(['id' => 'color'])) }}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-md-3">
					<label>Plan price</label>
				</div>
				<div class="col-md-9">
					<div class="row">
						<div class="col-md-8">
							{{ Form::text('price', null, array_merge(['class' => 'form-control validNumber', 'id' => 'price', 'placeholder' => 'Enter price'])) }}
						</div>
						@if ($errors->has('price'))
						<label class="error">{{ $errors->first('price') }}</label>
						@endif
					</div>
				</div>
			</div>
		</div>
		<!-- <div class="form-group">
		<div class="row">

		<div class="col-md-3">
		<label>Description</label>
	</div>
	<div class="col-md-9">
	{{-- Form::textarea('description', null, array_merge(['class' => 'form-control', 'id' => 'description', 'placeholder' => 'Enter description', 'rows' => 4, 'cols' => 54])) --}}
</div>
</div>
</div> -->
<div class="form-group">
	<div class="row">

		<div class="col-md-3">
			<label>Status</label>
		</div>
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-8">
					{{ Form::select('status', array('1' => 'Active', '0' => 'Inactive'), null, ['class' => 'form-control'] ) }}
				</div>
			</div>
		</div>
	</div>
</div>
<div class="form-group" id="Subscription_btns">
	<div class="row">
		<div class="col-md-6">
			{!! Form::hidden('id', $id) !!}
			{{ Form::submit($button_name, array_merge(['class' => 'btn btn-primary updateImage', 'id' => 'submit'])) }}
		</div>
		<div class="col-md-6 text-right">
			<a href="{{ $url.'/subscription_plan' }}" id="dissmiss" class="btn btn-danger">Dismiss</a>
		</div>
	</div>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/admin/subscriptionplan/subscriptionplan.blade.php
@extends('layouts.admin')
@section('content')
<div id="wrapper" class="editShow">
	<div class="page_title">
		<div class="row">
			<div class="col-md-9">
				<h1>Subscription plans</h1>
			</div>
			<div class="col-md-3 text-right">
				<!-- <a class="New_plan" href="{{ $url.'/new-subscription' }}">New Plan</a> -->
				<a class="New_plan" href="{{ route('subscription_plan.create') }}">Add Plan</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="subscription_boxes">
				<?php
				function color_blend_by_opacity( $foreground, $opacity, $background=null )
				{
					static $colors_rgb=array(); // stores colour values already passed through the hexdec() functions below.

					if( is_null($background) )
					$background = 'FFFFFF'; // default background.

					$pattern = '~^[a-f0-9]{6,6}$~i'; // accept only valid hexadecimal colour values.
					if( !@preg_match($pattern, $foreground)  or  !@preg_match($pattern, $background) )
					{
						trigger_error( "Invalid hexadecimal colour value(s) found", E_USER_WARNING );
						return false;
					}

					$opacity = intval( $opacity ); // validate opacity data/number.
					// print_r($opacity);die;
					if( $opacity>100  || $opacity<0 )
					{
						trigger_error( "Opacity percentage error, valid numbers are between 0 - 100", E_USER_WARNING );
						return false;
					}

					if( $opacity==100 )    // $transparency == 0
					return strtoupper( $foreground );
					if( $opacity==0 )    // $transparency == 100
					return strtoupper( $background );
					// calculate $transparency value.
					$transparency = 100-$opacity;

					if( !isset($colors_rgb[$foreground]) )
					{ // do this only ONCE per script, for each unique colour.
						$f = array(  'r'=>hexdec($foreground[0].$foreground[1]),
						'g'=>hexdec($foreground[2].$foreground[3]),
						'b'=>hexdec($foreground[4].$foreground[5])    );
						$colors_rgb[$foreground] = $f;
					}
					else
					{ // if this function is used 100 times in a script, this block is run 99 times.  Efficient.
						$f = $colors_rgb[$foreground];
					}

					if( !isset($colors_rgb[$background]) )
					{ // do this only ONCE per script, for each unique colour.
						$b = array(  'r'=>hexdec($background[0].$background[1]),
						'g'=>hexdec($background[2].$background[3]),
						'b'=>hexdec($background[4].$background[5])    );
						$colors_rgb[$background] = $b;
					}
					else
					{ // if this FUNCTION is used 100 times in a SCRIPT, this block will run 99 times.  Efficient.
						$b = $colors_rgb[$background];
					}

					$add = array(    'r'=>( $b['r']-$f['r'] ) / 100,
					'g'=>( $b['g']-$f['g'] ) / 100,
					'b'=>( $b['b']-$f['b'] ) / 100    );

					$f['r'] += intval( $add['r'] * $transparency );
					$f['g'] += intval( $add['g'] * $transparency );
					$f['b'] += intval( $add['b'] * $transparency );

					return sprintf( '%02X%02X%02X', $f['r'], $f['g'], $f['b'] );
				}
				?>
				@foreach ($getAllSubscriptionplan as $getSubscriptionplan)
				<div class="plan_row">
					<div class="row">
						<div class="col-md-10">
							<div class="Plan_box">
								<div class="row">
									<div class="col-md-3">
										<?php
										$foreground = str_replace("#","",$getSubscriptionplan['color']);
										$background = '0040A4';
										$o_color=@color_blend_by_opacity($foreground, 50, $background);
										// echo $o_color;
										?>
										<div class="revenue_box TotalBalance" style="background: {{ $getSubscriptionplan['color'] }};background: -webkit-linear-gradient(left, {{ $getSubscriptionplan['color'] }} 0%,{{ '#'.$o_color }} 100%);">
											<div class="Plan_img">
												@if($getSubscriptionplan['image'] == '')
												<img src="{{ asset('assets/images/free-plan.png') }}"/>
												@else
												<img src="{{ asset('assets/images/').'/'.$getSubscriptionplan['image'] }}"/>
												@endif
											</div>
											<div class="plan_name">
												{{ ucwords($getSubscriptionplan['title']) }}
											</div>
										</div>
									</div>
									<div class="col-md-3">
										<div class="revenue_box">
											<h4><span>{{ $getSubscriptionplan['uploads'] }}</span>uploads / month</h4>
										</div>
									</div>
									<div class="col-md-3">
										<div class="revenue_box">
											<h4><span>{{ $getSubscriptionplan['storage'].$getSubscriptionplan['storagelimit'] }}</span>storage</h4>
										</div>
									</div>
									<div class="col-md-3">
										<div class="revenue_box Today">
											@if($getSubscriptionplan['price'] != 0)
											<h3>{{ '$'.$getSubscriptionplan['price'] }}</h3>
											@else
											<h3>Free</h3>
											@endif
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-2">
							<div class="actions">
								<a href="javascript:void(0);" ref="{{ route('subscription_plan.edit', Crypt::encryptString($getSubscriptionplan['id'])) }}" id="edit-subscription-plan"><i class="fa fa-edit"></i></a>
								<a id="subscription-delete-plan" ref="{{ $getSubscriptionplan['id'] }}" href="javascript:void(0)"><i class="fa fa-trash"></i></a>
							</div>
						</div>
					</div>
				</div>
				@endforeach
			</div>
		</div>
	</div>
</div>
<div class="modal designModal" id="deleteSubscriptionPlan">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">
					<span class="header-text deleteHead"> Delete <span class="sellerHeadName">Subscription Plan</span> </span>
					<!-- <span class="header-text deactivateHead" style="display:none;"> Deactivate <span class="sellerHeadName">Buyer</span> </span>
					<span class="header-text activateHead" style="display:none;"> Activate <span class="sellerHeadName">Buyer</span> </span> -->
				</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<span class="body-text deleteText">Are you sure you want to delete this <span class="sellerText">plan</span>?</span>
				</div>
				@csrf
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
					<input type="hidden" id="sub-plan-id">
					<button type="button" class="btn btn-primary deleteSubscription">Yes</button>
					<input type="hidden" name="buyerId" id="buyerId">
				</div>
			</div>
		</div>
	</div>
</div>
@endsection