routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/', function () {
  return view('welcome');
});
Route::get('/sellers', 'Auth\RegisterController@showRegistrationForm')->name('seller');
Route::get('/confirm-account/{id}', 'Auth\RegisterController@confirmAccount')->name('confirm-account');
Route::get('/verify/{id}', 'Auth\RegisterController@verifyPage')->name('verify');
Route::get('/resend-register-email/{id}', 'Auth\RegisterController@resendRegisterEmail')->name('resend-register-email');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/front-search', 'HomeController@frontSearch');
Route::any('/sort-search', 'HomeController@searchShort');
Route::any('/template/{id}', 'HomeController@template');

Route::any('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::any('/support-center', 'HomeController@supportCenter')->name('support-center');
Route::get('/support-center/{id}/{question}', 'HomeController@supportCatoryWise');
Route::get('/support-center-answer/{id}/{question}', 'HomeController@supportCenterAnswer');

//Route::any('/support-search', 'HomeController@supportSearch');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('/events', 'HomeController@events')->name('events');
Route::get('/careers', 'HomeController@careers')->name('careers');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{slug}', 'HomeController@categoryWise')->name('category-wise');

Route::get('/payment-view/{id}', 'PaymentController@paymentView')->name('payment-view');

if(!function_exists('adminRoutes')) {
  function adminRoutes() {
    Route::group(['namespace' => 'Admin','middleware' => 'disablepreventback'], function()
    {
      Route::resource('dashboard', 'DashboardController');
      Route::get('settings', 'DashboardController@settings');
      Route::post('postCredentials', 'DashboardController@postCredentials');
      Route::post('updateimage', 'DashboardController@updateImage');
      Route::any('uploadSingleImage', 'DashboardController@uploadSingleImage');
      Route::post('deleteSingleImage', 'DashboardController@deleteSingleImage');
      Route::resource('sellers', 'SellersController');
      Route::any('search-sellers', 'SellersController@searchSellers');
      Route::post('change-status', 'SellersController@changeStatus');
      Route::any('entriesperpage', 'SellersController@entriesperpage');
      Route::post('deactivate-seller', 'SellersController@deactivateSeller');
      Route::resource('buyers', 'BuyersController');
      Route::any('search-buyers', 'BuyersController@searchBuyers');
      Route::any('entriesperpage', 'BuyersController@entriesperpage');
      Route::post('deactivate-buyer', 'BuyersController@deactivateBuyer');
      Route::resource('subscription_plan', 'SubscriptionplanController');
      Route::get('subscription', 'SubscriptionplanController@subscription');
      Route::get('new-subscription', 'SubscriptionplanController@newSubscription');
      Route::any('seller-design/{id}', 'SellersController@sellerDesign');
      Route::any('seller-logs/{id}/{designid}', 'SellersController@sellerLogs');

      Route::resource('events', 'EventController');

      Route::resource('orders', 'OrderController');
      Route::any('search-orders', 'OrderController@searchOrders');
      Route::get('order-details/{id}', 'OrderController@orderDetail');

      Route::get('transactions', 'TransactionController@index');
      Route::any('search-transaction', 'TransactionController@searchTransaction');

      Route::resource('faq', 'FaqController');
      Route::post('edit-modal', 'FaqController@editModal');
      // support center
      Route::resource('support-center', 'SupportCenterController');
      Route::post('edit-support-modal', 'SupportCenterController@editModal');

      Route::resource('support-category', 'SupportCategoryController');
      Route::post('support-category-modal', 'SupportCategoryController@supportCategoryModal');
    });
  }
}
if(!function_exists('buyerRoutes')) {
  function buyerRoutes() {
    Route::group(['namespace' => 'Buyer','middleware' => 'disablepreventback'], function()
    {
      Route::resource('/', 'DashboardController');
      //Route::resource('/dashboard', 'DashboardController');
      Route::resource('/dashboard', 'AccountSettingsController');
      Route::resource('/account-settings', 'AccountSettingsController');
      // Route::get('/resend-register-email/{id}', 'AccountSettingsController@resendRegisterEmail');
      Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
      Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfoBuyer');
      Route::post('/addRatingFaviorite','DashboardController@addRatingFaviorite')->name('addRatingFaviorite');
      Route::resource('/favourite','FavoriteController');
      Route::get('/downloads','FavoriteController@downloads');
      Route::get('/edit-template/{id}', 'FavoriteController@editTemplate');
      Route::any('search-downloads', 'FavoriteController@searchDownload');
      Route::any('uploadSingleImage', 'FavoriteController@uploadSingleImage');
      Route::any('/add-to-cart', 'CartController@addToCart');
      Route::any('/cart', 'CartController@index');
      Route::any('/cart-list', 'CartController@cartList');
      Route::any('/delete-update-cart-item', 'CartController@removeUpdateFromCart');
      Route::get('/checkout', 'CheckoutController@index')->name('checkout');
      Route::any('/payment-with-paypal', 'CheckoutController@paypalWithPayment')->name('payment.paypal');
      Route::get('/paypal-success', 'CheckoutController@paypalSuccess')->name('payment.paypalSuccess');

      Route::resource('orders', 'OrderController');
      Route::get('order-details/{id}', 'OrderController@orderDetail');
      Route::post('addRatingReview', 'FavoriteController@addRatingReview');
      Route::any('getRatingReview', 'FavoriteController@getRatingReview');


    });
  }
}
if(!function_exists('sellerRoutes')) {
  function sellerRoutes() {
    Route::group(['namespace' => 'Seller','middleware' => 'disablepreventback'], function() {
      //Route::group(['middleware' => 'plan'], function() {
      Route::group([], function() {
        Route::resource('/', 'DashboardController');
        Route::resource('dashboard', 'DashboardController');
        Route::resource('account-settings', 'AccountSettingsController');
        Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
        Route::resource('portfolio', 'DesignController');
        Route::post('geteditdesignmodal', 'DesignController@getEditDesignModal');
        Route::any('uploadSingleImage', 'DesignController@uploadSingleImage');

        Route::get('uploads', 'DesignController@getUploads')->name('uploads');
        Route::any('search-uploads', 'DesignController@searchUploads');
        Route::post('addFont', 'DesignController@addFont');

        Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfo');
        Route::any('/getImageEditor', 'DesignController@getImageEditor');

        Route::resource('earnings', 'EarningController');
        Route::any('search-earnings', 'EarningController@searchEarnings');
        Route::any('get_earning_details', 'EarningController@get_earning_details');
        Route::any('download-csv', 'EarningController@earningsExport');
      });

      Route::resource('choose_plan', 'ChoosePlanController');
    });
  }
}
Route::group(['prefix' => 'admin','middleware' => ['auth','role:admin','design']], function()
{
  adminRoutes();
});
Route::group(['prefix' => 'buyer','middleware' => ['auth','role:buyer']], function()
{
  buyerRoutes();
});
Route::group(['prefix' => 'seller','middleware' => ['auth','role:seller','verified']], function()
{
  sellerRoutes();
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;

class User extends Authenticatable implements MustVerifyEmailContract
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'name', 'user_name', 'email', 'password', 'image', 'phone', 'gender','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
      return $this->belongsToMany(Role::class);
    }

    public function business()
    {
      return $this->hasOne('App\Models\Business', 'user_id','id');
    }

    public function design()
    {
      return $this->hasMany('App\Models\Design', 'added_by','id');
    }

    public function getFullNameAttribute($value)
    {
      return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }
}

resources/views/admin/dashboard-old.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Admin Dashboard <a href="{{ route('subscription_plan.index') }}" style="float: right;">Subscription Plans</a></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('content')
	<div id="wrapper">
    	<div class="dashboard_slots">
            <div class="row">
                 <div class="col-md-4">
									<a href="<?php echo $url.'/sellers'; ?>">
                 	<div class="record_box seller_bx">
                    	<div class="row">
                        	<div class="col-md-6 col-6">
                            	<h4>Sellers</h4>
                                <h3>{{ $userCount['seller'] }}</h3>
                            </div>
                            <div class="col-md-6 col-6 text-center">
                            	<img src="{{ asset('assets/images/seller_img.png') }}"/>
                            </div>
                        </div>
                    </div>
									</a>
                 </div>
                 <div class="col-md-4">
								<a href="<?php echo $url.'/buyers'; ?>">
                 	<div class="record_box user_bx">
                    	<div class="row">
                        	<div class="col-md-6 col-6">
                            	<h4>Users</h4>
                                <h3>{{ $userCount['buyer'] }}</h3>
                            </div>
                            <div class="col-md-6 col-6 text-center">
                            	<img src="{{ asset('assets/images/Users_img.png') }}"/>
                            </div>
                        </div>
                    </div>
									</a>
                 </div>
                 <div class="col-md-4">
									 <a href="<?php echo $url.'/orders'; ?>">
                 	<div class="record_box orders_bx">
                    	<div class="row">
                        	<div class="col-md-6 col-6">
                            	<h4>Orders</h4>
                                <h3>{{ $userCount['orders'] }}</h3>
                            </div>
                            <div class="col-md-6 col-6 text-center">
                            	<img src="{{ asset('assets/images/Orders_img.png') }}"/>
                            </div>
                        </div>
                    </div>
									</a>
                 </div>
            </div>
            <div class="row">
            	<div class="col-md-12">
                	<div class="graph_panel">
                    	<div class="row">
            				<div class="col-md-6">
                            	<div class="Graph">
                                	<div class="graph_img_panel">
	                                	<img src="{{ asset('assets/images/graph1.png') }}"/>
                                    </div>
                                    <div class="graph_img_text">
	                                	<h4>Users activity</h4>
                                        <ul>
                                        	<li><span class="seller_color">&nbsp;</span>Sellers</li>
                                            <li><span class="users_color">&nbsp;</span>Users</li>
                                            <li><span class="admin_color">&nbsp;</span>Admin login</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                            	<div class="Graph">
                                	<div class="graph_img_panel text-center">
	                                	<img src="{{ asset('assets/images/graph2.png') }}"/>
                                    </div>
                                    <div class="graph_img_text">
	                                	<h4>Seller transactions</h4>
                                        <h5>change in % this month</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
@endsection

resources/views/admin/order-detail.blade.php
@extends('layouts.admin')
@section('content')
<section class="main_content_wrapper searchSection">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title_heading text-center">
          <h2>Order Details</h2>
        </div>
      </div>
      <div class="col-md-6">
        <div class="title_heading text-left details_order">
          <h4>Billing Address</h4>
          <p class="name_billing">{{ $result->order_details->full_name }}</p>
          <p class="order_num">{{ $result->order_details->shipping_email }}</p>
          <p>{{ $result->order_details->shipping_address.' '.$result->order_details->shipping_town.' '.$result->order_details->shipping_state }}</p>
          <p><span>Phone: </span>{{ $result->order_details->shipping_phone }}</p>
          <p><span>Shipping method: </span>@if($result->shipping == 0) Regular @else Express @endif</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="title_heading text-right">
          <a href="{{ URL('/buyer/orders') }}" class="btn btn-primary">Back To Order</a>
        </div>
      </div>
    </div>
    <div class="designer_uploads_section">
      <div class="uploads_panel">
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive" id="paginationData">
              <table class="table">
                <thead>
                  <tr>
                    <th>No.</th>
                    <th style="width:130px;">Design</th>
                    <th style="font-size:0;width: 161px;">Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total Price</th>
                  </tr>
                </thead>
                <tbody>
                  @php
                  $total_price = 0;
                  @endphp

                  @foreach($result['order_items'] as $index => $list)
                  <tr class="favTr">
                    <td>{{ $index+1 }}</td>
                    <td><img class="myImg" src="{{ asset("assets/images/seller-design/".$list['design_img']) }}" alt="{{ $list['name'] }}" /></td>
                    <td><a href="{{ URL('/template/'.Crypt::encrypt($list['design_id'])) }}" >{{ $list['design_name'] }}</a></td>
                    <td>{{ Helper::numberFormat($list['price']) }}</td>
                    <td>{{ $list['qty'] }}</td>
                    <td>{{ Helper::numberFormat($list['total_price']) }}</td>
                  </tr>
                  @endforeach
                  <tr class="noFound1">
                    <td colspan="4">
                    </td>
                    <td class="text-center">Sub Total
                    </td>
                    <td class="over_total">{{ Helper::numberFormat($result->subtotal) }}
                    </td>
                  </tr>
                  <tr class="noFound1">
                    <td colspan="4">
                    </td>
                    <td class="text-center">Shipping
                    </td>
                    <td class="over_total"> @if($result->shipping == 0) FREE @else {{ Helper::numberFormat($result->shipping) }} @endif
                    </td>
                  </tr>
                  <tr class="noFound1">
                    <td colspan="4">
                    </td>
                    <td class="text-center">Total Price
                    </td>
                    <td class="over_total">{{ Helper::numberFormat($result->total_amount) }}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.admin')
@section('content')
<div id="wrapper">
	<div class="page_title">
		<div class="row">
			<div class="col-md-12">
				<h1>Settings</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="setting_panel">
				<div class="form-group">
					<label>Username</label><span>{{ Auth::user()->name }}</span>
				</div>
				<div class="form-group">
					<label>Role</label><span>Master admin </span>
				</div>
				<div class="form-group">
					<label>Password</label><span><input value="54564565" readonly type="password"/>
						<a id="change-admin-password" href="javascript:void(0)">Change password</a></span>
					</div>
					<div class="form-group">
						<label>Profile image</label>
						<span>
							<span class="Profile_image_box">
								<img src="{{ asset('assets/images/profile/'.Auth::user()->image) }}"/>
							</span>
							<a id="changeAdminImage" href="javascript:void(0)">Change profile image</a>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal designModal" id="changeAdminImageModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">
						<span class="header-text deleteHead"> Change <span class="sellerHeadName">Image</span> </span>
					</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<form method="post" enctype="multipart/form-data" action="{{ $url.'/updateimage' }}" class="col-lg-12 changeImageForm">
						<!-- <form method="post" name="single_upload_form" id="single_upload_form" enctype="multipart/form-data" action=" singleSalonUploadImage"> -->
						<input type="hidden" name="image_form_submit" value="1"/>
						<label>Select Image</label>
						<span class="clearfix"></span>
						<span id="singleImageCheck"></span>
						<span class="add-multiple-images">
							<span class="upload-img btn btn-file singleSalon" id="mainImagesnew">
								<!-- <span class="fileupload-exists">Upload Image</span> -->
								<input type="button" name="mainImages" id="mainImages1" accept="image/x-png, image/gif, image/jpeg" value="Upload Image">
							</span>
						</span>
						<div id="images_preview">
						</div>
						<!-- </form> -->
						<label class="error" style="display:none;" id="user_photo-error">Please Select Image</label>
						<label class="error" style="display:none;" id="user_photo-valierror">Invalid File Upload</label>

						@csrf
						<div class="modal-footer">
							{{Form::submit('Update', ['class' => 'btn btn-primary updateImage','disabled'=>'disabled'])}}
						</div>
						{{Form::close()}}
					</div>
				</div>
			</div>
		</div>
		<div class="modal designModal" id="changeAdminPasswordModal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">
							<span class="header-text deleteHead"> Change <span class="sellerHeadName">Password</span> </span>
						</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
					<div class="modal-body">
						<form method="post" action="{{ $url.'/postCredentials' }}" class="col-lg-12" id="changePassword-form">

							<div class="form-group">
								<input type="password" name="password" id="password" class="form-control" value="" placeholder="Old Password">
							</div>
							<div class="form-group">
								<input type="password" name="new_password" id="new_password" class="form-control" value="" placeholder="New Password">
							</div>
							<div class="form-group">
								<input type="password" name="confirm_password" id="confirm_password" class="form-control" value="" placeholder="Confirm Password">
							</div>
							@csrf
							<div class="modal-footer">
								<button type="submit" class="btn btn-primary">Update</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<div class="imagesNew" style="display:none;">
			@include('imgedit2')
		</div>
		@endsection