routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/', function () {
  return view('welcome');
});
Route::get('/sellers', 'Auth\RegisterController@showRegistrationForm')->name('seller');
Route::get('/confirm-account/{id}', 'Auth\RegisterController@confirmAccount')->name('confirm-account');
Route::get('/verify/{id}', 'Auth\RegisterController@verifyPage')->name('verify');
Route::get('/resend-register-email/{id}', 'Auth\RegisterController@resendRegisterEmail')->name('resend-register-email');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/front-search', 'HomeController@frontSearch');
Route::any('/sort-search', 'HomeController@searchShort');
Route::any('/template/{id}', 'HomeController@template');

Route::any('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::any('/support-center', 'HomeController@supportCenter')->name('support-center');
Route::get('/support-center/{id}/{question}', 'HomeController@supportCatoryWise');
Route::get('/support-center-answer/{id}/{question}', 'HomeController@supportCenterAnswer');

//Route::any('/support-search', 'HomeController@supportSearch');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('/events', 'HomeController@events')->name('events');
Route::get('/careers', 'HomeController@careers')->name('careers');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{slug}', 'HomeController@categoryWise')->name('category-wise');

Route::get('/payment-view/{id}', 'PaymentController@paymentView')->name('payment-view');

if(!function_exists('adminRoutes')) {
  function adminRoutes() {
    Route::group(['namespace' => 'Admin','middleware' => 'disablepreventback'], function()
    {
      Route::resource('dashboard', 'DashboardController');
      Route::get('settings', 'DashboardController@settings');
      Route::post('postCredentials', 'DashboardController@postCredentials');
      Route::post('updateimage', 'DashboardController@updateImage');
      Route::any('uploadSingleImage', 'DashboardController@uploadSingleImage');
      Route::post('deleteSingleImage', 'DashboardController@deleteSingleImage');
      Route::resource('sellers', 'SellersController');
      Route::any('search-sellers', 'SellersController@searchSellers');
      Route::post('change-status', 'SellersController@changeStatus');
      Route::any('entriesperpage', 'SellersController@entriesperpage');
      Route::post('deactivate-seller', 'SellersController@deactivateSeller');
      Route::resource('buyers', 'BuyersController');
      Route::any('search-buyers', 'BuyersController@searchBuyers');
      Route::any('entriesperpage', 'BuyersController@entriesperpage');
      Route::post('deactivate-buyer', 'BuyersController@deactivateBuyer');
      Route::resource('subscription_plan', 'SubscriptionplanController');
      Route::get('subscription', 'SubscriptionplanController@subscription');
      Route::get('new-subscription', 'SubscriptionplanController@newSubscription');
      Route::any('seller-design/{id}', 'SellersController@sellerDesign');
      Route::any('seller-logs/{id}/{designid}', 'SellersController@sellerLogs');

      Route::resource('events', 'EventController');

      Route::resource('orders', 'OrderController');
      Route::any('search-orders', 'OrderController@searchOrders');
      Route::get('order-details/{id}', 'OrderController@orderDetail');

      Route::get('transactions', 'TransactionController@index');
      Route::any('search-transaction', 'TransactionController@searchTransaction');

      Route::resource('faq', 'FaqController');
      Route::post('edit-modal', 'FaqController@editModal');
      // support center
      Route::resource('support-center', 'SupportCenterController');
      Route::post('edit-support-modal', 'SupportCenterController@editModal');

      Route::resource('support-category', 'SupportCategoryController');
      Route::post('support-category-modal', 'SupportCategoryController@supportCategoryModal');
    });
  }
}
if(!function_exists('buyerRoutes')) {
  function buyerRoutes() {
    Route::group(['namespace' => 'Buyer','middleware' => 'disablepreventback'], function()
    {
      Route::resource('/', 'DashboardController');
      //Route::resource('/dashboard', 'DashboardController');
      Route::resource('/dashboard', 'AccountSettingsController');
      Route::resource('/account-settings', 'AccountSettingsController');
      // Route::get('/resend-register-email/{id}', 'AccountSettingsController@resendRegisterEmail');
      Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
      Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfoBuyer');
      Route::post('/addRatingFaviorite','DashboardController@addRatingFaviorite')->name('addRatingFaviorite');
      Route::resource('/favourite','FavoriteController');
      Route::get('/downloads','FavoriteController@downloads');
      Route::get('/edit-template/{id}', 'FavoriteController@editTemplate');
      Route::any('search-downloads', 'FavoriteController@searchDownload');
      Route::any('uploadSingleImage', 'FavoriteController@uploadSingleImage');
      Route::any('/add-to-cart', 'CartController@addToCart');
      Route::any('/cart', 'CartController@index');
      Route::any('/cart-list', 'CartController@cartList');
      Route::any('/delete-update-cart-item', 'CartController@removeUpdateFromCart');
      Route::get('/checkout', 'CheckoutController@index')->name('checkout');
      Route::any('/payment-with-paypal', 'CheckoutController@paypalWithPayment')->name('payment.paypal');
      Route::get('/paypal-success', 'CheckoutController@paypalSuccess')->name('payment.paypalSuccess');

      Route::resource('orders', 'OrderController');
      Route::get('order-details/{id}', 'OrderController@orderDetail');
      Route::post('addRatingReview', 'FavoriteController@addRatingReview');
      Route::any('getRatingReview', 'FavoriteController@getRatingReview');


    });
  }
}
if(!function_exists('sellerRoutes')) {
  function sellerRoutes() {
    Route::group(['namespace' => 'Seller','middleware' => 'disablepreventback'], function() {
      //Route::group(['middleware' => 'plan'], function() {
      Route::group([], function() {
        Route::resource('/', 'DashboardController');
        Route::resource('dashboard', 'DashboardController');
        Route::resource('account-settings', 'AccountSettingsController');
        Route::post('/changePassword','AccountSettingsController@changePassword')->name('changePassword');
        Route::resource('portfolio', 'DesignController');
        Route::post('geteditdesignmodal', 'DesignController@getEditDesignModal');
        Route::any('uploadSingleImage', 'DesignController@uploadSingleImage');

        Route::get('uploads', 'DesignController@getUploads')->name('uploads');
        Route::any('search-uploads', 'DesignController@searchUploads');
        Route::post('addFont', 'DesignController@addFont');

        Route::post('/changeGenralInfo','AccountSettingsController@changeGenralInfo')->name('changeGenralInfo');
        Route::any('/getImageEditor', 'DesignController@getImageEditor');

        Route::resource('earnings', 'EarningController');
        Route::any('search-earnings', 'EarningController@searchEarnings');
        Route::any('get_earning_details', 'EarningController@get_earning_details');
        Route::any('download-csv', 'EarningController@earningsExport');
      });

      Route::resource('choose_plan', 'ChoosePlanController');
    });
  }
}
Route::group(['prefix' => 'admin','middleware' => ['auth','role:admin','design']], function()
{
  adminRoutes();
});
Route::group(['prefix' => 'buyer','middleware' => ['auth','role:buyer']], function()
{
  buyerRoutes();
});
Route::group(['prefix' => 'seller','middleware' => ['auth','role:seller','verified']], function()
{
  sellerRoutes();
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/OrderItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
  protected $guarded = [];
  public $timestamps  = true;

  public function design()
  {
    return $this->hasOne('App\Models\Design', 'id','design_id');
  }

  public function order()
  {
    return $this->hasOne('App\Models\Order', 'id','order_id');
  }

  public function getTotalPricesAttribute()
  {
    return '$ '.number_format((float)$this->total_price, 2, '.', ',');
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;

class User extends Authenticatable implements MustVerifyEmailContract
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'name', 'user_name', 'email', 'password', 'image', 'phone', 'gender','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
      return $this->belongsToMany(Role::class);
    }

    public function business()
    {
      return $this->hasOne('App\Models\Business', 'user_id','id');
    }

    public function design()
    {
      return $this->hasMany('App\Models\Design', 'added_by','id');
    }

    public function getFullNameAttribute($value)
    {
      return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }
}

app/Http/Controllers/Seller/AccountSettingsController.php
<?php

namespace App\Http\Controllers\Seller;

use Hash;
use Session;
use DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Models\Business;



class AccountSettingsController extends Controller
{
  public $prefix='';
  public function __construct()
  {
    $this->prefix='seller';
  }
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $userId = Auth::user()->id;
    $businessData = User::with("business")->where('id',$userId)->first()->toArray();
    //echo "<pre>"; print_r($businessData); die;
    return view($this->prefix.'/accountsettings',['data'=>[$businessData]]);
  }


  public function changePassword(Request $request)
  {
    if(Auth::Check())
    {
      $request_data = $request->All();
      $messages = [
        'password.required' => 'Please enter current password',
        'new_password.required' => 'Please enter new password',
      ];
      $validator = \Validator::make($request_data, [
        'password' => 'required',
        'new_password' => 'required|same:new_password',
        'confirm_password' => 'required|same:new_password',
      ], $messages);
      if($validator->fails())
      {
        DB::rollback();
        $errors             = $validator->errors();
        $res['success']     = false;
        $res['formErrors']  = true;
        $res['errors']      = $errors;
        echo json_encode($res);
        die();
      }
      else
      {
        $current_password = Auth::User()->password;
        if(Hash::check($request_data['password'], $current_password))
        {
          $user_id = Auth::User()->id;
          $obj_user = User::find($user_id);
          $obj_user->password = Hash::make($request_data['new_password']);;
          $obj_user->save();
          $res['success']         = true;
          $res['url']             = 'account-settings';
          $res['delayTime']       = '2000';
          $res['success_message']   = 'New Password has been changed.';
        }
        else
        {
          DB::rollback();
          $res['success']         = false;
          $res['delayTime']       = '2000';
          $res['error_message']   = 'Please enter correct current password.';
        }
      }
      echo json_encode($res);
      die();
    }
  }
  /**
  * Update Seller Genral Info.
  *
  * @return \Illuminate\Http\Response
  */
  public function changeGenralInfo(Request $request)
  {
    $imageName = "";
    if(!empty($request->profileimage)) {
      $image = $request->profileimage;
      if($image != '') {
        $fullName = $image->getClientOriginalName();
        $name = pathinfo($fullName, PATHINFO_FILENAME);
        $imageName  =  $name.'_'.time().'.'.$image->getClientOriginalExtension();
        $image->move('assets/images/profile/', $imageName);

        $userData = [
          'first_name' => $request->first_name,
          'last_name' => $request->last_name,
          'name' => $request->first_name.' '.$request->last_name,
          'gender' => $request->gender,
          'phone' => $request->phone,
          'image' => $imageName
        ];
      }
    }else{
      $userData = [
        'first_name' => $request->first_name,
        'last_name' => $request->last_name,
        'name' => $request->first_name.' '.$request->last_name,
        'gender' => $request->gender,
        'phone' => $request->phone
      ];
    }

    $userId = Auth::user()->id;

    $userUpdate = User::where('id', $userId)->update($userData);

    $businessUpdate = Business::where('user_id', $userId)->update([
      'businessname' => $request->businessname,
      'category' => $request->cat,
      'city' => $request->city,
      'state' => $request->state,
      'zip' => $request->zip,
      'description' => $request->description,
      'phone' => $request->contact
    ]);

      if($userUpdate)
      {
        DB::commit();
        $data['success']          = true;
        $data['url']              = 'account-settings';
        $data['delayTime']        = '2000';
        $data['success_message']  = 'Updated Successfully.';
      }
      else
      {
        DB::rollback();
        $data['success']          = false;
        $data['delayTime']        = '3000';
        $data['success_message']  = 'Something went wrong.';
      }
      echo json_encode($data); die();

  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    //
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    //
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    //
  }
}

app/Http/Controllers/Seller/BusinessController.php
<?php

namespace App\Http\Controllers\Seller;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BusinessController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/seller/chooseplan.blade.php
@extends('layouts.seller')
@section('content')
<section class="main_content_wrapper">
  <?php // echo "<pre>"; print_r($getAllSubscriptionplan); echo "</pre>"; ?>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title_heading text-center">
          <h2>Choose subscription plan</h2>
        </div>
      </div>
    </div>
    <div class="row">
      @foreach ($getAllSubscriptionplan as $plan)
      <div class="col-md-3 padding_0">
        <div class="subscribe_panel {{ str_replace(' ', '-', strtolower($plan['title'])) }}">
          <div class="plan_head">
            <img src="{{ asset('assets/images') }}/{{ $plan['image'] }}"/>
            <h4>{!! str_replace(' ', '<br>', $plan['title']) !!}</h4>
          </div>
          <div class="plan_content">
            <ul>
              <li>{{ $plan['uploads'] }}<span>@if($plan['price']<=0) uploads available @else uploads/month @endif</span></li>
              <li>{{ $plan['storage'] }}{{ $plan['storagelimit'] }}<span>storage</span></li>
            </ul>
            @if($plan['price']<=0)
            <h3>free</h3>
            @else
            <h3>${{ $plan['price'] }}</h3>
            @endif
          </div>
          <div class="plan_button">
            <a href="{{ route('payment-view', ['id' => encrypt($plan['id']) ]) }}" class="btn">Choose</a>
          </div>
        </div>
      </div>
      @endforeach



      <!--div class="col-md-3 padding_0">
      <div class="subscribe_panel entry-level">
      <div class="plan_head">
      <img src="{{ asset('assets/images/entry-level.png') }}"/>
      <h4>Entry <br/>Level</h4>
    </div>
    <div class="plan_content">
    <ul>
    <li>50<span>uploads/month</span></li>
    <li>100MB<span>storage</span></li>
  </ul>
  <h3>$49</h3>
</div>
<div class="plan_button">
<a href="#" class="btn">Choose</a>
</div>
</div>
</div>
<div class="col-md-3 padding_0">
<div class="subscribe_panel intermediate-plan">
<div class="plan_head">
<img src="{{ asset('assets/images/intermediate-plan.png') }}"/>
<h4>Intermediate <br/>Plan</h4>
</div>
<div class="plan_content">
<ul>
<li>150<span>uploads/month</span></li>
<li>500MB<span>storage</span></li>
</ul>
<h3>$79</h3>
</div>
<div class="plan_button">
<a href="#" class="btn">Choose</a>
</div>
</div>
</div>
<div class="col-md-3 padding_0">
<div class="subscribe_panel expert-level">
<div class="plan_head">
<img src="{{ asset('assets/images/expert-level.png') }}"/>
<h4>Expert <br/>Level</h4>
</div>
<div class="plan_content">
<ul>
<li>250<span>uploads/month</span></li>
<li>1GB<span>storage</span></li>
</ul>
<h3>$99</h3>
</div>
<div class="plan_button">
<a href="#" class="btn">Choose</a>
</div>
</div>
</div-->

</div>
</div>
</section>
@endsection

resources/views/seller/dashboard.blade.php
@extends('layouts.seller')
@section('content')
<section class="main_content_wrapper">
  <div class="container">
    @include('seller.menu')
    <div class="last_latest_recent">
      <div class="panel">
        <div class="row">
          <div class="col-md-9">
            <h4 class="section_head">Last sold item</h4>
            @if(count($last_order) == 1)
            <div class="sold_panel">
              <div class="row">
                <div class="col-md-6">
                  <div class="last_sold_box_img">
                    <img src="{{ asset('assets/images/seller-design/').'/'.$last_order->design->designimage }}"/>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="last_sold_box_cont">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="detail_box">
                          <h5>{{ $last_order->design->name }}</h5>
                          <p>{{ $last_order->design->business_category->name }}</p>
                          <p>Price <span>{{ $last_order->total_prices }}</span></p>
                        </div>
                        <div class="detail_box">
                          <h5>Customer Details</h5>
                          <div class="row">
                            <div class="col-md-5">
                              <div class="customer_img">
                                @if($last_order->order->buyer->image != '')
                                <img src="{{ asset('assets/images/profile/').'/'.$last_order->order->buyer->image }}"/>
                                @else
                                <img src="{{ asset('assets/images/dummy-male.png') }}"/>
                                @endif
                              </div>
                            </div>
                            <div class="col-md-7 padding_0">
                              <div class="address">{{ $last_order->order->order_details->full_name }}<br/>{{ $last_order->order->order_details->shipping_address.' '.$last_order->order->order_details->shipping_town.' '.$last_order->order->order_details->shipping_state }}<br/>{{ $last_order->order->order_details->shipping_email }}</div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-4 padding_left_0">
                        <div class="paid_unpaid">
                          <i class="fa fa-check"></i>
                          <span class="check">Paid</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            @else
            No record found.
            @endif
          </div>
          <div class="col-md-3 text-center">
            <h6>Earnings</h6>
            <div class="total_balance">
              Total Balance<span> @if($all_order->sum('total_price')) {{ Helper::numberFormat($all_order->sum('total_price')) }} @else 0 @endif</span>
            </div>
            <div class="last_balance">
              <h6>Last Payment<span> @if(count($last_order) == 1) {{ $last_order->total_prices }} @else 0 @endif</span></h6>
            </div>
            <div class="transaction_history">
              <a href="{{ URL('/seller/earnings') }}">View transaction history</a>
            </div>
          </div>
        </div>
      </div>

      <div class="panel" id="Latest_added">
        <h4 class="section_head">Latest added items</h4>
        @if(!$result->isEmpty())
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div id="news-slider10" class="owl-carousel">
                @foreach ($result as $list)
                <div class="post-slide10">
                  <img src="{{ URL("/")."/assets/images/seller-design/".$list->designimage }}" alt="{{ $list->name }}" />
                </div>
                @endforeach
              </div>
            </div>
          </div>
        </div>
        @else
        No record found.
        @endif
      </div>

      <div class="panel" id="Recent_activity">
        <h4 class="section_head">Recent activity</h4>
        <ul>
          @if($added_design)
          @foreach($added_design as $key=>$des)
          @if($key<= 1)
          <li><span>Uploaded 1 image in category {{ $des->design->business_category->name }}</span><a href="{{ URL('/template/').'/'.Crypt::encrypt($des->log_id) }}">details</a></li>
          @endif
          @endforeach
          @endif
          @if(count($last_order) == 1)
          <li><span>Sold {{ $last_order->qty }} item from category {{ $last_order->design->business_category->name }}</span><a href="{{ URL('/seller/earnings') }}">details</a></li>
          @endif
            @if((count($last_order) == 0) && $added_design->isEmpty() )
            No record found.
            @endif
        </ul>
      </div>
    </div>
  </div>
</div>
</section>
@endsection

resources/views/seller/design-ajax.blade.php
<div class="row">
  @if(!empty($result))
  @foreach ($result as $list)
  <div class="col-md-3">
    <div class="portfolio_box">
      <div class="portfolio_img">
        <img src="{{ URL("/")."/assets/images/seller-design/".$list->designimage }}" alt="{{ $list->name }}" />
      </div>
      <div class="portfolio_content">
        <h5>{{ ucfirst($list->name) }}</h5>
        <h5><strong>{{ Helper::numberFormat($list->price) }}</strong></h5>
        <p>{{ $list->business_category->name }}</p>
      </div>
    </div>
  </div>
  @endforeach
  @else
  No Record Found
  @endif
</div>
{{ $result->links('pagination.pagination_links') }}

resources/views/seller/design.blade.php
@extends('layouts.seller')
@section('content')
<section class="main_content_wrapper">
  <div class="container">
    @include('seller.menu')
    <div class="designer_portfolio_section">
      <div class="row">
        <div class="col-md-6">
          <div class="filter">
            <a href="javascript:void(0)" class="filterBy" data-filterBy="desc">Filter by <span>Month <i class="fa fa-arrow-down"></i></span></a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="Add_designss text-right">
            <button id="dialogButton" class="btn btn-primary design_modal"><i class="fa fa-plus"></i> Add Design</button>
          </div>
        </div>
      </div>
      <div class="portfolio_panel" id="paginationData">
        <div class="row">
          @if(!$result->isEmpty())
          @foreach ($result as $list)
          <div class="col-md-3">
            <div class="portfolio_box">
              <div class="portfolio_img">
                <img src="{{ URL("/")."/assets/images/seller-design/".$list->designimage }}" alt="{{ $list->name }}" />
              </div>
              <div class="portfolio_content">
                <h5>{{ ucfirst($list->name) }}</h5>
                <h5><strong>{{ Helper::numberFormat($list->price) }}</strong></h5>
                <p>{{ $list->business_category->name }}</p>
              </div>
            </div>
          </div>
          @endforeach
          @else
          <span class="col-md-12 text-center">
            No Record Found
          </span>
        </div>
        {{ $result->links('pagination.pagination_links') }}
        @endif
      </div>
    </div>
  </div>
</section>

<div id="Add_Design" class="hidden designModal" style="display:none;">
  @php
  $designImageRequired = 1;
  @endphp
  @include('seller.designmodel')
</div>
@include('includes.admin.delete-modal')
@endsection

resources/views/seller/get-earning-details.blade.php
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">{{ $result->name }}</h4>
    </div>
      <div class="row">
        <div class="col-md-6">
          <div class="View_Earnings_image">
            <img src="{{ asset("assets/images/seller-design/".$result->designimage) }}" alt="{{ $result->name }}" title="{{ $result->name }}"/>
          </div>
        </div>
        <div class="col-md-6">
          <div class="Earnings_Price_Cont">
            <h4>{{ Helper::numberFormat($result->price) }}</h4>
            <p>{{ $result->description }}</p>
          </div>
          <div class="Earnings_Category">
            <h5><span>Category</span>{{ $result->business_category->name }}</h5>
            <h5><span>Downloads</span><em>{{ $result->orderItems->sum('qty') }}</em></h5>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="customer_list_panel">
            <h4>Last customer details</h4>
            <div class="row">
              <div class="col-md-12">
                @if(count($last_order) == 1)
                <div class="detail_box">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="customer_img">
                        @if($last_order->order->buyer->image != '')
                        <img src="{{ asset('assets/images/profile/').'/'.$last_order->order->buyer->image }}"/>
                        @else
                        <img src="{{ asset('assets/images/dummy-male.png') }}"/>
                        @endif
                      </div>
                      <div class="address">{{ $last_order->order->order_details->full_name }}<br/>{{ $last_order->order->order_details->shipping_address.' '.$last_order->order->order_details->shipping_town.' '.$last_order->order->order_details->shipping_state }}<br/>{{ $last_order->order->order_details->shipping_email }}</div>
                    </div>
                    <div class="col-md-6">
                      <div class="paid_unpaid">
                        <i class="fa fa-check"></i>
                        <span class="check">Paid</span>
                      </div>
                    </div>
                  </div>
                </div>
                @else
                No record found.
                @endif
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="customer_list_panel">
            <h4>Customer list <a href="#" class="link-text">View entire list > </a></h4>
            <div class="table-responsive">
              <table class="table">
                @if(!$all_order->isEmpty())
                @foreach ($all_order as $user)
                <tr>
                  <td class="user_img">
                    <span>
                      @if($user->buyer->image != '')
                      <img src="{{ asset('assets/images/profile/').'/'.$user->buyer->image }}"/>
                      @else
                      <img src="{{ asset('assets/images/dummy-male.png') }}"/>
                      @endif
                    </span>
                  </td>
                  <td class="username">{{ $user->buyer->name }}</td>
                  <td class="text-right"><a href="#" class="link-text">details</a></td>
                </tr>
                @endforeach
                @else
                No record found.
                @endif
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>